# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:

  backendBZ:
    runs-on: ubuntu-18.04
    - name: Set selected color
    run: echo '::set-output name=SELECTED_COLOR::green'
    run: echo 'hi mom!'
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Deploy the site with netlify-cli
    - name: Deploy Site
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: netlify deploy --dir=client --build --prod      
